name: kraftcloud/kraftcloud
resources:
    kraftcloud_instance Resource - terraform-provider-kraftcloud:
        subCategory: ""
        description: Allows the creation of KraftCloud instances.
        name: kraftcloud_instance Resource - terraform-provider-kraftcloud
        title: kraftcloud_instance Resource - terraform-provider-kraftcloud
        argumentDocs:
            args: (List of String)
            autostart: (Boolean)
            boot_time_us: (Number)
            created_at: (String)
            dns: (String)
            env: (Map of String)
            handlers: (Set of String)
            image: (String)
            internal_port: (Number)
            memory_mb: (Number)
            port: (Number)
            private_ip: (String)
            service_group: (String)
            state: (String)
            uuid: (String) Unique identifier of the instance
        importStatements:
            - terraform import kraftcloud_instance.example 550e8400-e29b-41d4-a716-446655440000
